### ISSUE TITLE
Extended Attributes Do Not Work On ext2/ext3

### ISSUE THREAD

**Issue by alicoderepo** [gkostka/lwext4#21]
Hello

The [documentation ](https://github.com/gkostka/lwext4#supported-ext234-features) of lwext4 mentions support for extended attributes for both ext2 and ext3. However, when the file system is configured for either of these versions, ext4_xattr_list() fails to retrieve the extended attributes associated with a file. 

It is not clear whether the documentation has a typo in it or if the code needs to be updated.

Following is a summary of the debugging done for the issue:

The following if-condition seems to be the source of the problem:
`uint16_t ext4_inode_get_extra_isize(struct ext4_sblock *sb,
				    struct ext4_inode *inode)
{
	if (ext4_sb_feature_ro_com(sb, EXT4_FRO_COM_EXTRA_ISIZE))
		return to_le16(inode->extra_isize);
	else
		return 0;
}`

Both EXT2 and EXT3 are configured without the EXT4_FRO_COM_EXTRA_ISIZE option.

**Comment by gkostka** [comment]
Hi,

I'll look into this. It might be a problem in a code but I can't say anything more right now.

**Comment by ngkaho1234** [comment]
Hi,
Would you mind telling me more about the information of the EXT2/EXT3 filesystem you created, i.e. the output of stats command from debugfs ?

**Comment by gkostka** [comment]
Short code example would be also useful for us. Something like:
ext4_xattr_set
...
ext4_xattr_list

**Comment by ngkaho1234** [comment]
After taking sometime investigating into the code (also linux 4.9.13), I found something funny...
ext2.ko in linux/fs/ext2 is incompatible with ext4.ko in linux/fs/ext4 even though both of them can mount an ext2 filesystem. The situation in lwext4 is the similar as in ext2.ko - ext2.ko is not able to deal with EAs in inode body no matter how large the inode size is.

**Comment by ngkaho1234** [comment]
After taking sometime investigating into the code (also linux 4.9.11), I found something rather funny...
ext2.ko in linux/fs/ext2 is incompatible with ext4.ko in linux/fs/ext4 even though both of them can mount an ext2 filesystem. The situation in lwext4 is the similar as in ext2.ko - ext2.ko is not able to deal with EAs in inode body no matter how large the inode size is, which is also what you have observed with lwext4.

EDIT: As a fix I think being compatible with behavior of ext4.ko should be fine, since nowadays most of the recent kernel builds (4.9.11-1-ARCH) only have ext4.ko enabled.
EDIT: lwext4 can deal with EAs in inode body when RO_COMPAT_EXTRA_ISIZE flag is enabled in superblock, and at the same time if inode size is larger or equal to 256.

**Comment by ngkaho1234** [comment]
Hi,
Please pull my fork https://github.com/ngkaho1234/lwext4 and see if these changes work as expected.

**Comment by gkostka** [comment]
Changes are now on my master branch as well.

**Comment by alicoderepo** [comment]
I tried the changes and they seem to work.

Thanks for the prompt response and fix guys!

**Comment by gkostka** [comment]
Great! We are looking forward to get more feedback.

Regards
Grzegorz
