### ISSUE TITLE
Free Block Count issue

### ISSUE THREAD

**Issue by rajeshvenkataraman** [gkostka/lwext4#26]
I seem to be having some kind of memory blocks leaking and can't figure out why. I am using the EXT4 format with journaling. After the filesystem is initialized I get the following stats
Inode Count	114688
Free Inode Count	114677
Block Count	458752
Free Block Count	437098
Block Size	2048
Block Group Count	56
Blocks Per Group	8192
Inodes Per Group	2048

 And after I fill the system with files I delete all the files. But when I look at the stats on this empty filesystem some blocks are lost. 

Inode Count	114688
Free Inode Count	114677
Block Count	458752
Free Block Count	437085
Block Size	2048
Block Group Count	56
Blocks Per Group	8192
Inodes Per Group	2048
The Free Block Count reduced from 437098 to 437085.  Is this expected behaviour? Any ideas why this is occurring?

**Comment by gkostka** [comment]
Hi,

have you tried to run ext4.fsck? Is should detect any block leakage. Are you using lwext4_generic as an example?

**Comment by rajeshvenkataraman** [comment]
I am running the filesystem on an embedded non linux platform. I won't be able to run ext4.fsck. I am using the lwext4_generic as reference. I also tried turning off the journalling but still saw the same issue.

**Comment by gkostka** [comment]
Maybe it is good idea to run some of your code of Linux platform and try to reproduce this potential bug.
Without this, it would be hard for me to find and fix it...

Another question. Is free block count increasing every time after you run your code? Or it is occurring once after first code test code run?

**Comment by rajeshvenkataraman** [comment]
I think after generating thousands of file in a directory and deleting all the files some, blocks remain associated to this directory. It looks like it keep all the file names in the block. When the directory is deleted all the blocks are freed. Is this the expected behavior? 

On an other topic, in the ext4_mkfs.c I had changed the function 
static uint32_t compute_blocks_per_group(struct ext4_mkfs_info *info)
{
        //return info->block_size * 8;
        return info->block_size * 4;
}
I did that change to improve performance by changing the block size from 4K to 8K and still keeping the same block group size. But with that change I had lots of issue. Is there a reason the block group size needs to be multiple of 8.

**Comment by gkostka** [comment]
> 
I think after generating thousands of file in a directory and deleting all the files some, blocks remain associated to this directory. It looks like it keep all the file names in the block. When the directory is deleted all the blocks are freed. Is this the expected behavior?
> 

If I understand you correctly yes, it is expected behavior.

> 
I did that change to improve performance by changing the block size from 4K to 8K and still keeping the same block group size. But with that change I had lots of issue. Is there a reason the block group size needs to be multiple of 8.
> 

Yes. It has to be multiple of 8 (number of bits in byte). If you would like to improve performance please increase your cache block count (CONFIG_BLOCK_DEV_CACHE_SIZE).
