### ISSUE TITLE
Check is too late

### ISSUE THREAD

**Issue by awana81** [gkostka/lwext4#37]
https://github.com/gkostka/lwext4/blob/96b4563a7ed9f603a6f66cbe21cbd1acb2f0294a/src/ext4.c#L998

If the function at line 994 that sets r fails, more than likely the call at 997 is going to blow up. The check should be before the result is used. Also O_CREAT on say /nonexistdir1/nonexistdir2/newfile looks like it will try to create all the directories in this loop, but I don't think that will work, and it's not typical behavior for O_CREAT in APIs.

**Comment by gkostka** [comment]
1 Fixed here: https://github.com/gkostka/lwext4/commit/dc0347cc9b3ea74da062c553dbcdc541c030f114

I know that O_CREATE behaviour is a little bit different than standard says. Why you are saying that it is not working? Could you paste here an example where it causing a problems.

Thanks for feedback.

**Comment by awana81** [comment]
I may have messed something else up, but when I tried to make /mountpoint/nonexistdir1/nonexistdir2/newfile it appeared to go into an infinite loop when making nonexistdir2. I may have missed it, but I didn't spot in the code where it updates to get the next portion of the path when linking the name.

**Comment by rajeshvenkataraman** [comment]
I think this problem is in the ext4_dir_dx_add_entry(). The string length is calculated from strlen() and not using the length passed to ext4_dir.c:ext4_dir_add_entry(). After changing the r = ext4_dir_dx_add_entry(parent, child, name); to r = ext4_dir_dx_add_entry(parent, child, name_len, name);  inside ext4_dir_add_entry() and adding name_len as a parameter to the function in ext4_dir_idx.c:ext4_dir_dx_add_entry(struct ext4_inode_ref *parent, struct ext4_inode_ref *child, uint32_t name_len, const char *name) and removing the local variable uint32_t name_len = strlen(name); this issue is fixed.

Do you think of any side effect because of this change?

**Comment by gkostka** [comment]
@rajeshvenkataraman thank you for analysis. Could you create pull request for this. I'm on holidays now and I can't introduce this change soon. PR will makes this easier.

**Comment by gkostka** [comment]
You need to fork lwext4 and push branch to your fork. After that you will be able to create PR here. Thanks.

**Comment by gkostka** [comment]
Fixed here: 1aa974054274a4f59dfa59c88bb9a85461eca113
